Add cardsize select to more views and load HQ preview when on large cardsize
fxhash/fxhash-website pull request #138
Opened 2022-05-19 18:47 UTC by maerzhase

- fix #130 

This PR implements caching preview urls by key in the `Card` component. This allows us to switch the previewUrl to HQ url when large card size is selected. 

@ciphrd As I already mentioned `CardExplorer` on retained routes, caused a race condition when updating the `--card-size` css variable. All retained `CardExplorer` views would receive the pathname change which would cause in inconsistent card sizes. Therefore I implemented a check that compares the "basePath" of the `router.pathname` with the `cardSizeScope` and only update if they match. This obviously comes now on one condition: `cardSizeScope` need to match routes. For now that works just fine because marketplace cards should all be in the same scope (`"marketplace" === "marketplace"`). But it would be a problem if we want to have the same `cardSizeScope` on "/abc" and "/xyz". 
I really couldn't think of a cleaner solution. What do you think?

Shall we had the card size selection also to the `u/<name>/creations` and `u/<name>/collection` pages?

2022-09-07 17:23 UTC, maerzhase commented
merge conflicts solved. ready for review

2022-09-26 12:39 UTC, ciphrd requested changes
I noticed that the card size feature is not working on a project iterations:

![image](https://user-images.githubusercontent.com/18054507/192278220-afffba0c-b9a7-4714-80c4-7cf2edcffee2.png)

2022-09-27 08:11 UTC, maerzhase commented
good catch gonna have a look

2022-10-14 14:48 UTC, ciphrd requested changes
Looking good!

Only detail: the setting is missing from the user collection, I think it'd be great in there

2022-11-15 18:50 UTC, GemN approved these changes
LGTM! Good job :)

2022-11-15 18:53 UTC, GemN commented
Actually I found a bug (or undocumented feature?) 
Open filters in iterations with "big card size" 
![Capture d’écran 2022-11-15 à 18 52 20](https://user-images.githubusercontent.com/13420650/202001953-66f0a499-50fc-4343-9b19-bf816e52bd81.png)

2022-11-15 19:41 UTC, maerzhase commented
thanks @GemN !! good issue you found and i fixed another leek we discussed!!

2022-11-15 20:23 UTC, GemN approved these changes

2022-11-21 15:50 UTC, maerzhase commented on src/components/Exploration/CardsExplorer.tsx
> +    [cardSizeScope, settings.cardSize]
Since card size is now provided by scope we check if we have a card size saved or use default size

2022-11-21 15:50 UTC, maerzhase commented on src/containers/User/UserGenerativeTokens.tsx
> +        <CardsContainer cardSize={270}>
Since user creations don't have the cards explroerer we don't show card size select and provide the default card-size to the container

2023-01-10 10:18 UTC, merged