keep focus on editor when adding blocks
fxhash/fxhash-website pull request #250
Opened 2022-07-07 20:54 UTC by maerzhase

~~pointer down events are used instead of click to
prevent the cursor loosing focus in the contenteditable
pointer event is used for compatibility with different
input devices. when using add block the selection
is set to the add block target path.~~

We dont use pointerDown, but found a way to restore the selection after the focus is lost. see comments below

- fix #230

2022-07-15 14:35 UTC, maerzhase commented on src/components/NFTArticle/SlateEditor/Elements/RenderElements.tsx
> +    })
After a block is added, we check if the created element is focusable. If `true` we call the elements `focus()` method. If `false` we restore the selection by setting the focus to the editor and finding the deepest leaf path of the created node and set the selection there.

2022-07-15 14:36 UTC, maerzhase commented on src/components/NFTArticle/elements/Figure.tsx
> +  }
When a figure is focused. We want to restore selection to the caption inside the figure.

2022-07-20 18:23 UTC, ciphrd requested changes
It seems to be working well for paragraphs.
However, when clicking an image there is a weird glitch and the focus on the caption doesn't seem to be working anymore (see video attached).

https://user-images.githubusercontent.com/18054507/180054788-27622a25-c92a-4fff-892c-71116bbfcc6c.mp4

Please also make sure it's working with all the blocks, I didn't check.

2022-07-22 16:01 UTC, maerzhase commented
@ciphrd turns out that we must ensure to render the `children` that are provided by slate, also if the component is e.g. avoid component. This allows us to create a proper slate selection and the we can actually just use `useSelected` hook from `slate-react` to determine if a block is selected and trigger and effect to e.g. focus the textarea. I've implemented it for the KatexBlock. 

please note: the media embed is not yet implemented on this branch.

2022-07-22 16:02 UTC, maerzhase commented on src/components/NFTArticle/SlateEditor/Elements/Blocks.tsx
> +	{children}
we must ensure that we render the `children` otherwise will throw an error when the selection is pointing to this block

2022-07-25 16:13 UTC, ciphrd approved these changes
LGTM

2022-07-25 16:13 UTC, merged