add softbreak plugin
fxhash/fxhash-website pull request #306
Opened 2022-08-01 08:00 UTC by maerzhase

-  fix #304

2022-08-01 21:42 UTC, GemN commented
I think it's too permissive at the moment, you're not checking the node type, it could add undesired side effects 
```js
  editor.insertSoftBreak = () => {
    // check the node type is p / ul / ol etc
    // insert \n
    insertSoftBreak() // to allow other plugins to work if they manipulate soft break
  }
```

2022-08-02 06:37 UTC, maerzhase commented
sure we can add that, i am not sure if its necessary though. softlinebreak is only triggered on text nodes. that should already exclude all custom blocks. 

but we can also retrieve the node by cursor position and do a check for the type.

2022-08-02 17:32 UTC, maerzhase commented
I included the changes proposed by @GemN 👍

2022-08-03 13:02 UTC, ciphrd requested changes
I believe it's good to check for the block type, as we want to avoid any weird side effect.

There is an issue in the markdown transformation, this is the string which gets computed:

```md
This is a test&#x20;
We can have multiline now, great

Another test
```

(see here https://gateway.fxhash-dev2.xyz/ipfs/Qmcfk4M1jwkFiN3FhEw1m1PoZX5nqjSPKqGHxuFKAM7qgV)

Resulting in the viewer not displaying the multiline properly:

![image](https://user-images.githubusercontent.com/18054507/182613818-d2d7c0a1-c84c-4f02-a1a3-604f44a77148.png)

I believe the resulting markdown should be:

```md
This is a test
We can have multiline now, great

Another test
```

This is by default rendered like that by markdown viewers:
> This is a test We can have multiline now, great

As there is no support for backline in paragraphs. It needs to be added.

So basically this is the expected markdown with backline in a paragraph:

```md
This is a line
This is another line, same paragraph

Another paragraph
```

2022-08-05 20:05 UTC, maerzhase commented
the encoding comes from the mdast-util-to-markdown: https://github.com/syntax-tree/mdast-util-to-markdown/commit/108450c5e3dc013f8e9f7119b63ed8feddff7a7b

when i started to replace the encoded whitespaces it also breaks the newlines. @ciphrd i am not sure how to resolve this issue

2026-07-07 23:14 UTC, closed without merging