Feature/press kit page
fxhash/fxhash-website pull request #509
Opened 2022-12-07 20:03 UTC by maerzhase

_wip_

2022-12-14 16:25 UTC, GemN requested changes
## Desktop 

Pressing "back button" on desktop should move back to the previous section (it only update the url at the moment)

<img width="729" alt="Capture d’écran 2022-12-14 à 16 55 02" src="https://user-images.githubusercontent.com/13420650/207645887-579b5734-6609-462d-9655-4dc7cfdbd228.png">

- Errors on some videos 
- The display could be a bit spaced in case of errors

Good work on desktop! 

## Improvements

I think every event / exhibs / museums should be dated and ordered by most recents.
I will make a copy in discord of this since it's related to product
<img width="647" alt="Capture d’écran 2022-12-14 à 17 12 03" src="https://user-images.githubusercontent.com/13420650/207649356-fd20ee69-b730-45d4-b8e6-d00ce1b65a21.png">

## Mobile
I have a few suggestions for mobile since it has not been provided in figma

### logo

<img width="309" alt="Capture d’écran 2022-12-14 à 17 04 51" src="https://user-images.githubusercontent.com/13420650/207646934-5d6f61d4-cbc8-4239-9dcd-2c4e5d224541.png">

- "full logo" and other H2 should be 20px on mobile (refer to the mobile version on figma, try to match titles size, ping on discord if needed)
- text-align center for download buttons with a bit of padding (check with viewport width 320px)
- "Download the full presskit at once." download .zip should be block width 100% under

### medias

<img width="391" alt="Capture d’écran 2022-12-14 à 17 19 13" src="https://user-images.githubusercontent.com/13420650/207650369-15e73735-817b-4f9e-8a9a-006d9825155d.png">

- like in logo, update h2 titles as expected
- when an dropdown is open, let the dropdown be position: sticky on top, that way we always have the title of event and we can easily close it by taping on it

<img width="333" alt="Capture d’écran 2022-12-14 à 17 20 56" src="https://user-images.githubusercontent.com/13420650/207650750-d6c621f3-b8fb-4f71-8251-b9a23ff6cc46.png">

- Images should be clickable and open in a new page (or as a modal preview with cover if you feel like it)

2022-12-14 20:39 UTC, maerzhase commented
@GemN thanks for your helpful review. i did the mobile pass and added all the other things.
instead of giving more space for the errors on video load i decided to hide them. 
back/forward navigation should work now.

2022-12-15 13:19 UTC, GemN requested changes
<img width="292" alt="Capture d’écran 2022-12-15 à 13 30 57" src="https://user-images.githubusercontent.com/13420650/207860795-57733e70-bccc-4a3b-9a24-a3b84177ec6a.png">
<img width="310" alt="Capture d’écran 2022-12-15 à 13 30 50" src="https://user-images.githubusercontent.com/13420650/207860804-972906f1-0766-4a74-a999-ee2388038e8f.png">

There is a bit of extra gap in mobile tab nav, check on the explore tab, underline must finish where the next item begin, and there is no extra padding on the last element.

The sticky dropdown works well in desktop however in mobile, it has some weird and inconsistent behavior (check video)

[screen-recording.webm](https://user-images.githubusercontent.com/13420650/207869065-ea7c2f54-2781-40ed-8b0b-4d0cf5aacdff.webm)


As an improvement, when a dropdown collapse scroll back to the origin position of the dropdown, else we lose the focus in the page because of the layout shift

2022-12-15 17:20 UTC, GemN approved these changes

2022-12-15 20:25 UTC, GemN approved these changes

2022-12-15 20:36 UTC, merged