Fix: Collaborator badges overflowing Objkt card
fxhash/fxhash-website pull request #548
Opened 2023-01-20 16:29 UTC by jpescada

The PR fixes #546.

The changes only address the bug so it’s no longer breaking the layout. 

The nice-to-have part to show the full list of collaborators from the card will be addressed in a separate PR as a feature.

**Current issue:**

![Screenshot 2023-01-20 at 16 26 34](https://user-images.githubusercontent.com/136504/213751531-22ea0f90-4942-4876-812c-a01132d7e3bb.png)

**After the fix:**

![Screenshot 2023-01-20 at 16 25 26](https://user-images.githubusercontent.com/136504/213751255-2dd838ab-1855-461a-bbb2-33fe46dcdd77.png)

2023-01-20 18:09 UTC, jpescada commented
Actually only fixes the issue while the card is displayed in the user’s collection, not on the objkt page. 
(Looking into the issue again)

2023-01-21 02:47 UTC, jpescada commented
@maerzhase Had to move things around and tweak the alignment, but it looks good now. 
Ready to review 👍

2023-01-22 01:10 UTC, jpescada commented
Design question: do we need the link icon on the card? What purpose does it serve? 
The collaborator avatars/names aren’t links. Find it misleading. 
Removing it would also simplify the collab badge layout… 😄

2023-01-23 11:52 UTC, GemN commented
Hi @jpescada, 
First of all, thank you for your contribution! 

<img width="523" alt="Capture d’écran 2023-01-23 à 12 31 27" src="https://user-images.githubusercontent.com/13420650/214029424-8cf382ff-1ea8-40e8-a073-c93812aa1984.png">

For a first iteration, in term of design it meets the acceptance criterias, however there are few areas that need to be fixed.

***

#### 1. Mobile

<img width="399" alt="Capture d’écran 2023-01-23 à 12 33 32" src="https://user-images.githubusercontent.com/13420650/214029770-4a4faf7e-7d3b-471c-bab0-6880c3549a6a.png">

In mobile, a large gap is visible. Only the `<Spacing />` of 16px must be between the collab badge and the title.

***

#### 2. Cards
<img width="309" alt="Capture d’écran 2023-01-23 à 12 37 12" src="https://user-images.githubusercontent.com/13420650/214030464-6dc712e0-a8f1-49c8-8dee-9fe172f0453f.png">

The collab badge on objkt / gentk cards behave weirdly. 

<img width="325" alt="Capture d’écran 2023-01-23 à 12 40 50" src="https://user-images.githubusercontent.com/13420650/214031048-0882ed16-a63c-47d0-9a75-ca7081a0cc98.png">

The current behavior must be kept: hovering on an avatar must display the username (and its verification check if any)

***

#### 3. Improvements

This is optional (if you can't, we will do it no worries), at the moment the limitation of badge displayed is 3 no matters what size the container have remaining. 

Based on the fixed size of the badge, display dynamically more badges, ex:

<img width="1305" alt="Capture d’écran 2023-01-23 à 12 47 06" src="https://user-images.githubusercontent.com/13420650/214032261-b0656941-b44d-45aa-b95d-9a24b9885f49.png">

50/60% of the container can be filled with avatar, that way if you display 8 avatar it would be (+9)

<img width="324" alt="Capture d’écran 2023-01-23 à 12 50 09" src="https://user-images.githubusercontent.com/13420650/214032801-64ff94f5-8d6a-443f-be31-78f5dd800572.png">
60/70% can be filled on cards - while keeping **the same hover behavior** (hovering flex the avatar name)

2023-01-23 11:52 UTC, GemN requested changes
See above

2023-01-23 14:23 UTC, maerzhase commented
@GemN thanks for the review 👍 

@jpescada about the link(s). we discussed in the team and created a new issue: https://github.com/fxhash/fxhash-website/issues/550

2023-01-24 20:42 UTC, jpescada commented
Thanks for the feedback. I’m going to review this tomorrow to address those issues.

2023-04-11 16:23 UTC, maerzhase commented
the devil was in the detail. closing this one in favour of #685. 
nonetheless thanks very much @jpescada for the effort! really appreciate it! 🐰 ❤️

2023-04-11 16:23 UTC, closed without merging