feat(search): search can be minimized on mobile
fxhash/fxhash-website pull request #99
Opened 2022-04-28 16:56 UTC by GemN

fixes #82 

A few notes:
I introduce two new hooks with this PR.
- useClickOutside: for component behavior purpose, allow to check if the user clicked outside an element
- useWindowsSize: for component behavior purpose, allow to check the window size in real time. 
Even if it's preferable to use css to handle breakpoints, sometimes we can't use css only to handle behavior (see component SearchInput)

2022-04-29 11:36 UTC, GemN commented
I thought:
- User writes his search, then click on sort by. However I just notice this process does not work currently because it would require to trigger search on blur. 

Your suggestion:
- Hide the sort when the input search is focused
The implementation should not be that hard because I can add a callback "onMinimize" that will send his state back to the parent.

Should I minimise the sort or completely hide it ? 
Completely hide it force this user flow:
- user write his search
- user "enter"
- page scroll to top marker, the search unfocus
- user can select a sort

Minimizing the sort allow this user flow:
- user write his search
- user click on the sort minimized
- the search trigger on blur, the input minimize, the sort expand and user can select his sort choice
(it saves a click)

At the moment I'd rather do the first userflow because i'm not sure we want to trigger the search on blur?

2022-05-05 09:34 UTC, ciphrd commented
I think we really don't want to trigger a search on blur (not an expected UX pattern).

While it would make sense to trigger a search on blur **if and only if** the minimized sort is clicked after, I think it makes the UX weird and would require a few implementation tricks (to prevent the auto scroll for instance).

I'd rather opt for hiding the sort altogether when the search input is focused, forcing the trigger of the search with "enter". And then if the user wants a different sort they can change it.

2022-05-05 15:48 UTC, ciphrd requested changes
Small detail: the change breaks the color of the search input background on dark theme:
![image](https://user-images.githubusercontent.com/18054507/166962083-0c0a543b-3d03-40da-9f21-f19b0d04a585.png)

2022-05-05 15:48 UTC, ciphrd commented on src/components/Input/SearchInput.tsx
> +      onMinimize(newState);
Can be onlined 
```js
onMinimize?.(newState)
```

2022-05-05 16:04 UTC, ciphrd approved these changes
LGTM

2022-05-05 16:04 UTC, merged